New log file opened at Mon May 18 01:10:02 PDT 2015 by 5880@BASHTOP
Taking next connection to: 63532
New client attempting to connect on port: 63533-63532
  Address = /169.254.254.68:63532
This client on port 63533 has uuid 6aca7278-b725-4570-b535-8fa04172ea92 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-6aca7278-b725-4570-b535-8fa04172ea92
Taking next connection to: 63532
New client attempting to connect on port: 63534-63532
  Address = /169.254.254.68:63532
Handshake exception on socket: 63534
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 63532
New client attempting to connect on port: 63535-63532
  Address = /169.254.254.68:63532
This client on port 63535 has uuid dd01728f-4c87-4f54-b38c-e4be1cf53860 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-6aca7278-b725-4570-b535-8fa04172ea92, activator-dd01728f-4c87-4f54-b38c-e4be1cf53860
Taking next connection to: 63532
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 63532
